[package]
authors = ["Bitfinity Network"]
categories = ["cryptography::cryptocurrencies"]
description = "API types definition for EVMC"
edition = "2021"
homepage = "https://github.com/infinity-swap/evmc-did"
include = ["src/**/*", "LICENSE", "README.md"]
license = "MIT"
name = "evmc-did"
repository = "https://github.com/infinity-swap/evmc-did"
version = "0.2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.3"
candid = "0.8"
eth-signer = { git = "https://github.com/infinity-swap/eth-signer" }
derive_more = "0.99"
ethereum-types = "0.14"
# infinityswap.atlassian.net/browse/EPROD-153 - We are currently depending on a commit, will be removed when new version is released
ethers-core = { git = "https://github.com/infinity-swap/ethers-rs", default-features = false, package = "ethers-core", branch = "evmc_fork" }
hex = "0.4"
ic-stable-structures = { git = "https://github.com/infinity-swap/canister-sdk", branch = "EPROD-381-investigate-the-evmc-canister-upgrade-problems", package = "ic-stable-structures" }
ic-storage = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-storage", tag = "v0.3.54" }
is20-token = { git = "https://github.com/infinity-swap/IS20", tag = "v1.10.44" }
jsonrpc-core = "18.0"
log = "0.4"
num = "0.4"
once_cell = "1.16"
rlp = "0.5"
serde = "1.0"
serde_bytes = "0.11"
serde_json = "1.0"
sha2 = "0.10"
sha3 = "0.10"
thiserror = "1.0"

[dev-dependencies]
rand = { version = "0.8", features = ["std_rng", "small_rng"] }

[profile.dev]
debug = true

# Set the settings for all dependencies (but not this crate itself or any workspace member).
# This includes build dependencies.
# Level range is from 0 (default for dev) to 3 (default for release)
[profile.dev.package."*"]
opt-level = 0

# Set the settings for build scripts and proc-macros.
[profile.dev.build-override]
opt-level = 2

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
